#-------------------------------------------------

# [Legal]
# Copyright 2022 Esri.

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# [Legal]

#-------------------------------------------------

INCLUDEPATH += \
    "$$SAMPLEPATHCPP/Analysis/AnalyzeHotspots" \
    "$$SAMPLEPATHCPP/Analysis/AnalyzeViewshed" \
    "$$SAMPLEPATHCPP/Analysis/DistanceMeasurementAnalysis" \
    "$$SAMPLEPATHCPP/Analysis/Geotriggers" \
    "$$SAMPLEPATHCPP/Analysis/LineOfSightGeoElement" \
    "$$SAMPLEPATHCPP/Analysis/LineOfSightLocation" \
    "$$SAMPLEPATHCPP/Analysis/StatisticalQuery" \
    "$$SAMPLEPATHCPP/Analysis/StatisticalQueryGroupSort" \
    "$$SAMPLEPATHCPP/Analysis/ViewshedCamera" \
    "$$SAMPLEPATHCPP/Analysis/ViewshedGeoElement" \
    "$$SAMPLEPATHCPP/Analysis/ViewshedLocation" \
    "$$SAMPLEPATHCPP/CloudAndPortal/AddItemsToPortal" \
    "$$SAMPLEPATHCPP/CloudAndPortal/IntegratedWindowsAuthentication" \
    "$$SAMPLEPATHCPP/CloudAndPortal/PortalUserInfo" \
    "$$SAMPLEPATHCPP/CloudAndPortal/SearchForWebmap" \
    "$$SAMPLEPATHCPP/CloudAndPortal/ShowOrgBasemaps" \
    "$$SAMPLEPATHCPP/CloudAndPortal/TokenAuthentication" \
    "$$SAMPLEPATHCPP/DisplayInformation/AddGraphicsWithRenderer" \
    "$$SAMPLEPATHCPP/DisplayInformation/BuildLegend" \
    "$$SAMPLEPATHCPP/DisplayInformation/ControlAnnotationSublayerVisibility" \
    "$$SAMPLEPATHCPP/DisplayInformation/CreateSymbolStylesFromWebStyles" \
    "$$SAMPLEPATHCPP/DisplayInformation/CustomDictionaryStyle" \
    "$$SAMPLEPATHCPP/DisplayInformation/DisplayGrid" \
    "$$SAMPLEPATHCPP/DisplayInformation/GODictionaryRenderer_3D" \
    "$$SAMPLEPATHCPP/DisplayInformation/GODictionaryRenderer" \
    "$$SAMPLEPATHCPP/DisplayInformation/GOSymbols" \
    "$$SAMPLEPATHCPP/DisplayInformation/IdentifyGraphics" \
    "$$SAMPLEPATHCPP/DisplayInformation/Picture_Marker_Symbol" \
    "$$SAMPLEPATHCPP/DisplayInformation/QueryFeaturesWithArcadeExpression" \
    "$$SAMPLEPATHCPP/DisplayInformation/ReadSymbolsFromMobileStyle" \
    "$$SAMPLEPATHCPP/DisplayInformation/ShowCallout" \
    "$$SAMPLEPATHCPP/DisplayInformation/ShowLabelsOnLayers" \
    "$$SAMPLEPATHCPP/DisplayInformation/ShowPopup" \
    "$$SAMPLEPATHCPP/DisplayInformation/Simple_Marker_Symbol" \
    "$$SAMPLEPATHCPP/DisplayInformation/Simple_Renderer" \
    "$$SAMPLEPATHCPP/DisplayInformation/SketchOnMap" \
    "$$SAMPLEPATHCPP/DisplayInformation/SymbolizeShapefile" \
    "$$SAMPLEPATHCPP/DisplayInformation/Unique_Value_Renderer" \
    "$$SAMPLEPATHCPP/EditData/AddFeaturesFeatureService" \
    "$$SAMPLEPATHCPP/EditData/ContingentValues" \
    "$$SAMPLEPATHCPP/EditData/DeleteFeaturesFeatureService" \
    "$$SAMPLEPATHCPP/EditData/EditAndSyncFeatures" \
    "$$SAMPLEPATHCPP/EditData/EditFeatureAttachments" \
    "$$SAMPLEPATHCPP/EditData/EditFeaturesWithFeatureLinkedAnnotation" \
    "$$SAMPLEPATHCPP/EditData/EditKmlGroundOverlay" \
    "$$SAMPLEPATHCPP/EditData/EditWithBranchVersioning" \
    "$$SAMPLEPATHCPP/EditData/UpdateAttributesFeatureService" \
    "$$SAMPLEPATHCPP/EditData/UpdateGeometryFeatureService" \
    "$$SAMPLEPATHCPP/Features/ControlTimeExtentTimeSlider" \
    "$$SAMPLEPATHCPP/Features/FeatureLayerChangeRenderer" \
    "$$SAMPLEPATHCPP/Features/FeatureLayerDictionaryRenderer" \
    "$$SAMPLEPATHCPP/Features/FeatureLayerFeatureService" \
    "$$SAMPLEPATHCPP/Features/FeatureLayerGeodatabase" \
    "$$SAMPLEPATHCPP/Features/FeatureLayerGeoPackage" \
    "$$SAMPLEPATHCPP/Features/FeatureLayerQuery" \
    "$$SAMPLEPATHCPP/Features/FeatureLayerSelection" \
    "$$SAMPLEPATHCPP/Features/FilterByDefinitionExpressionOrDisplayFilter" \
    "$$SAMPLEPATHCPP/Features/GenerateGeodatabase" \
    "$$SAMPLEPATHCPP/Features/ListRelatedFeatures" \
    "$$SAMPLEPATHCPP/Features/ServiceFeatureTableCache" \
    "$$SAMPLEPATHCPP/Features/ServiceFeatureTableManualCache" \
    "$$SAMPLEPATHCPP/Features/ServiceFeatureTableNoCache" \
    "$$SAMPLEPATHCPP/Geometry/Buffer" \
    "$$SAMPLEPATHCPP/Geometry/ClipGeometry" \
    "$$SAMPLEPATHCPP/Geometry/ConvexHull" \
    "$$SAMPLEPATHCPP/Geometry/CreateGeometries" \
    "$$SAMPLEPATHCPP/Geometry/CutGeometry" \
    "$$SAMPLEPATHCPP/Geometry/DensifyAndGeneralize" \
    "$$SAMPLEPATHCPP/Geometry/FormatCoordinates" \
    "$$SAMPLEPATHCPP/Geometry/GeodesicOperations" \
    "$$SAMPLEPATHCPP/Geometry/ListTransformations" \
    "$$SAMPLEPATHCPP/Geometry/NearestVertex" \
    "$$SAMPLEPATHCPP/Geometry/ProjectGeometry" \
    "$$SAMPLEPATHCPP/Geometry/SpatialOperations" \
    "$$SAMPLEPATHCPP/Geometry/SpatialRelationships" \
    "$$SAMPLEPATHCPP/Layers/AddEncExchangeSet" \
    "$$SAMPLEPATHCPP/Layers/ApplyMosaicRuleToRasters" \
    "$$SAMPLEPATHCPP/Layers/ApplyUniqueValuesWithAlternateSymbols" \
    "$$SAMPLEPATHCPP/Layers/ArcGISMapImageLayerUrl" \
    "$$SAMPLEPATHCPP/Layers/ArcGISTiledLayerUrl" \
    "$$SAMPLEPATHCPP/Layers/BlendRasterLayer" \
    "$$SAMPLEPATHCPP/Layers/BrowseOGCAPIFeatureService" \
    "$$SAMPLEPATHCPP/Layers/BrowseWfsLayers" \
    "$$SAMPLEPATHCPP/Layers/ChangeSublayerRenderer" \
    "$$SAMPLEPATHCPP/Layers/ChangeSublayerVisibility" \
    "$$SAMPLEPATHCPP/Layers/CreateAndSaveKmlFile" \
    "$$SAMPLEPATHCPP/Layers/DisplayAnnotation" \
    "$$SAMPLEPATHCPP/Layers/DisplayDimensions" \
    "$$SAMPLEPATHCPP/Layers/DisplayKml" \
    "$$SAMPLEPATHCPP/Layers/DisplayKmlNetworkLinks" \
    "$$SAMPLEPATHCPP/Layers/DisplayOgcApiFeatureCollection" \
    "$$SAMPLEPATHCPP/Layers/DisplaySubtypeFeatureLayer" \
    "$$SAMPLEPATHCPP/Layers/DisplayWfsLayer" \
    "$$SAMPLEPATHCPP/Layers/ExportTiles" \
    "$$SAMPLEPATHCPP/Layers/Feature_Collection_Layer" \
    "$$SAMPLEPATHCPP/Layers/FeatureCollectionLayerFromPortal" \
    "$$SAMPLEPATHCPP/Layers/FeatureCollectionLayerQuery" \
    "$$SAMPLEPATHCPP/Layers/FeatureLayerRenderingModeMap" \
    "$$SAMPLEPATHCPP/Layers/FeatureLayerRenderingModeScene" \
    "$$SAMPLEPATHCPP/Layers/FeatureLayerShapefile" \
    "$$SAMPLEPATHCPP/Layers/GroupLayers" \
    "$$SAMPLEPATHCPP/Layers/Hillshade_Renderer" \
    "$$SAMPLEPATHCPP/Layers/IdentifyKmlFeatures" \
    "$$SAMPLEPATHCPP/Layers/IdentifyRasterCell" \
    "$$SAMPLEPATHCPP/Layers/ListKmlContents" \
    "$$SAMPLEPATHCPP/Layers/LoadWfsXmlQuery" \
    "$$SAMPLEPATHCPP/Layers/ManageOperationalLayers" \
    "$$SAMPLEPATHCPP/Layers/OSM_Layer" \
    "$$SAMPLEPATHCPP/Layers/PlayAKmlTour" \
    "$$SAMPLEPATHCPP/Layers/QueryMapImageSublayer" \
    "$$SAMPLEPATHCPP/Layers/QueryOGCAPICQLFilters" \
    "$$SAMPLEPATHCPP/Layers/RasterColormapRenderer" \
    "$$SAMPLEPATHCPP/Layers/RasterFunctionService" \
    "$$SAMPLEPATHCPP/Layers/RasterLayerFile" \
    "$$SAMPLEPATHCPP/Layers/RasterLayerGeoPackage" \
    "$$SAMPLEPATHCPP/Layers/RasterLayerService"\
    "$$SAMPLEPATHCPP/Layers/RasterRenderingRule" \
    "$$SAMPLEPATHCPP/Layers/RasterRgbRenderer" \
    "$$SAMPLEPATHCPP/Layers/RasterStretchRenderer" \
    "$$SAMPLEPATHCPP/Layers/StyleWmsLayer" \
    "$$SAMPLEPATHCPP/Layers/TileCacheLayer" \
    "$$SAMPLEPATHCPP/Layers/VectorTiledLayerUrl" \
    "$$SAMPLEPATHCPP/Layers/Web_Tiled_Layer" \
    "$$SAMPLEPATHCPP/Layers/WmsLayerUrl" \
    "$$SAMPLEPATHCPP/Layers/WMTS_Layer" \
    "$$SAMPLEPATHCPP/Maps/ApplyScheduledMapUpdates" \
    "$$SAMPLEPATHCPP/Maps/BrowseBuildingFloors" \
    "$$SAMPLEPATHCPP/Maps/ChangeBasemap" \
    "$$SAMPLEPATHCPP/Maps/ChangeViewpoint" \
    "$$SAMPLEPATHCPP/Maps/CreateAndSaveMap" \
    "$$SAMPLEPATHCPP/Maps/DisplayDeviceLocation" \
    "$$SAMPLEPATHCPP/Maps/DisplayDeviceLocationWithNmeaDataSources" \
    "$$SAMPLEPATHCPP/Maps/DisplayDrawingStatus" \
    "$$SAMPLEPATHCPP/Maps/DisplayLayerViewDrawState" \
    "$$SAMPLEPATHCPP/Maps/DisplayMap" \
    "$$SAMPLEPATHCPP/Maps/DisplayOverviewMap" \
    "$$SAMPLEPATHCPP/Maps/DownloadPreplannedMap" \
    "$$SAMPLEPATHCPP/Maps/GenerateOfflineMap_Overrides" \
    "$$SAMPLEPATHCPP/Maps/GenerateOfflineMap" \
    "$$SAMPLEPATHCPP/Maps/GenerateOfflineMapLocalBasemap" \
    "$$SAMPLEPATHCPP/Maps/HonorMobileMapPackageExpiration" \
    "$$SAMPLEPATHCPP/Maps/IdentifyLayers" \
    "$$SAMPLEPATHCPP/Maps/ManageBookmarks" \
    "$$SAMPLEPATHCPP/Maps/MapLoaded" \
    "$$SAMPLEPATHCPP/Maps/MapReferenceScale" \
    "$$SAMPLEPATHCPP/Maps/MapRotation" \
    "$$SAMPLEPATHCPP/Maps/MinMaxScale" \
    "$$SAMPLEPATHCPP/Maps/MobileMap_SearchAndRoute" \
    "$$SAMPLEPATHCPP/Maps/OpenMapUrl" \
    "$$SAMPLEPATHCPP/Maps/OpenMobileMap_MapPackage" \
    "$$SAMPLEPATHCPP/Maps/ReadGeoPackage" \
    "$$SAMPLEPATHCPP/Maps/SetInitialMapArea" \
    "$$SAMPLEPATHCPP/Maps/SetInitialMapLocation" \
    "$$SAMPLEPATHCPP/Maps/SetMapSpatialReference" \
    "$$SAMPLEPATHCPP/Maps/SetMaxExtent" \
    "$$SAMPLEPATHCPP/Maps/ShowDeviceLocationUsingIndoorPositioning" \
    "$$SAMPLEPATHCPP/Maps/ShowLocationHistory" \
    "$$SAMPLEPATHCPP/Maps/ShowMagnifier" \
    "$$SAMPLEPATHCPP/Maps/TakeScreenshot" \
    "$$SAMPLEPATHCPP/Routing/ClosestFacility" \
    "$$SAMPLEPATHCPP/Routing/FindClosestFacilityToMultipleIncidentsService" \
    "$$SAMPLEPATHCPP/Routing/FindRoute" \
    "$$SAMPLEPATHCPP/Routing/FindServiceAreasForMultipleFacilities" \
    "$$SAMPLEPATHCPP/Routing/NavigateRoute" \
    "$$SAMPLEPATHCPP/Routing/OfflineRouting" \
    "$$SAMPLEPATHCPP/Routing/RouteAroundBarriers" \
    "$$SAMPLEPATHCPP/Routing/ServiceArea" \
    "$$SAMPLEPATHCPP/Scenes/AddAPointSceneLayer" \
    "$$SAMPLEPATHCPP/Scenes/AddIntegratedMeshLayer" \
    "$$SAMPLEPATHCPP/Scenes/Animate3DSymbols" \
    "$$SAMPLEPATHCPP/Scenes/AnimateImagesWithImageOverlay" \
    "$$SAMPLEPATHCPP/Scenes/BasicSceneView" \
    "$$SAMPLEPATHCPP/Scenes/ChangeAtmosphereEffect" \
    "$$SAMPLEPATHCPP/Scenes/ChooseCameraController" \
    "$$SAMPLEPATHCPP/Scenes/CreateTerrainSurfaceFromLocalRaster" \
    "$$SAMPLEPATHCPP/Scenes/CreateTerrainSurfaceFromLocalTilePackage" \
    "$$SAMPLEPATHCPP/Scenes/Display3DLabelsInScene" \
    "$$SAMPLEPATHCPP/Scenes/DisplaySceneLayer" \
    "$$SAMPLEPATHCPP/Scenes/DistanceCompositeSymbol" \
    "$$SAMPLEPATHCPP/Scenes/ExtrudeGraphics" \
    "$$SAMPLEPATHCPP/Scenes/FeatureLayerExtrusion" \
    "$$SAMPLEPATHCPP/Scenes/GetElevationAtPoint" \
    "$$SAMPLEPATHCPP/Scenes/OpenMobileScenePackage" \
    "$$SAMPLEPATHCPP/Scenes/OpenScene" \
    "$$SAMPLEPATHCPP/Scenes/OrbitCameraAroundObject" \
    "$$SAMPLEPATHCPP/Scenes/RealisticLightingAndShadows" \
    "$$SAMPLEPATHCPP/Scenes/SceneLayerSelection" \
    "$$SAMPLEPATHCPP/Scenes/ScenePropertiesExpressions" \
    "$$SAMPLEPATHCPP/Scenes/SurfacePlacement" \
    "$$SAMPLEPATHCPP/Scenes/Symbols" \
    "$$SAMPLEPATHCPP/Scenes/SyncMapViewSceneView" \
    "$$SAMPLEPATHCPP/Scenes/TerrainExaggeration" \
    "$$SAMPLEPATHCPP/Scenes/ViewContentBeneathTerrainSurface" \
    "$$SAMPLEPATHCPP/Scenes/ViewPointCloudDataOffline" \
    "$$SAMPLEPATHCPP/Search/FindAddress" \
    "$$SAMPLEPATHCPP/Search/FindPlace" \
    "$$SAMPLEPATHCPP/Search/OfflineGeocode" \
    "$$SAMPLEPATHCPP/Search/ReverseGeocodeOnline" \
    "$$SAMPLEPATHCPP/Search/SearchDictionarySymbolStyle" \
    "$$SAMPLEPATHCPP/UtilityNetwork/ConfigureSubnetworkTrace" \
    "$$SAMPLEPATHCPP/UtilityNetwork/CreateLoadReport" \
    "$$SAMPLEPATHCPP/UtilityNetwork/DisplayContentOfUtilityNetworkContainer" \
    "$$SAMPLEPATHCPP/UtilityNetwork/DisplayUtilityAssociations" \
    "$$SAMPLEPATHCPP/UtilityNetwork/PerformValveIsolationTrace" \
    "$$SAMPLEPATHCPP/UtilityNetwork/TraceUtilityNetwork"

HEADERS += \
    "$$SAMPLEPATHCPP/Analysis/AnalyzeHotspots/AnalyzeHotspots.h" \
    "$$SAMPLEPATHCPP/Analysis/AnalyzeViewshed/AnalyzeViewshed.h" \
    "$$SAMPLEPATHCPP/Analysis/DistanceMeasurementAnalysis/DistanceMeasurementAnalysis.h" \
    "$$SAMPLEPATHCPP/Analysis/Geotriggers/Geotriggers.h" \
    "$$SAMPLEPATHCPP/Analysis/LineOfSightGeoElement/LineOfSightGeoElement.h" \
    "$$SAMPLEPATHCPP/Analysis/LineOfSightLocation/LineOfSightLocation.h" \
    "$$SAMPLEPATHCPP/Analysis/StatisticalQuery/StatisticalQuery.h" \
    "$$SAMPLEPATHCPP/Analysis/StatisticalQueryGroupSort/StatisticalQueryGroupSort.h" \
    "$$SAMPLEPATHCPP/Analysis/StatisticalQueryGroupSort/StatisticResultListModel.h" \
    "$$SAMPLEPATHCPP/Analysis/ViewshedCamera/ViewshedCamera.h" \
    "$$SAMPLEPATHCPP/Analysis/ViewshedGeoElement/ViewshedGeoElement.h" \
    "$$SAMPLEPATHCPP/Analysis/ViewshedLocation/ViewshedLocation.h" \
    "$$SAMPLEPATHCPP/CloudAndPortal/IntegratedWindowsAuthentication/IntegratedWindowsAuthentication.h" \
    "$$SAMPLEPATHCPP/CloudAndPortal/TokenAuthentication/TokenAuthentication.h" \
    "$$SAMPLEPATHCPP/DisplayInformation/AddGraphicsWithRenderer/AddGraphicsWithRenderer.h" \
    "$$SAMPLEPATHCPP/DisplayInformation/BuildLegend/BuildLegend.h" \
    "$$SAMPLEPATHCPP/DisplayInformation/ControlAnnotationSublayerVisibility/ControlAnnotationSublayerVisibility.h" \
    "$$SAMPLEPATHCPP/DisplayInformation/CreateSymbolStylesFromWebStyles/CreateSymbolStylesFromWebStyles.h" \
    "$$SAMPLEPATHCPP/DisplayInformation/CustomDictionaryStyle/CustomDictionaryStyle.h" \
    "$$SAMPLEPATHCPP/DisplayInformation/DisplayGrid/DisplayGrid.h" \
    "$$SAMPLEPATHCPP/DisplayInformation/GODictionaryRenderer_3D/GODictionaryRenderer_3D.h" \
    "$$SAMPLEPATHCPP/DisplayInformation/GODictionaryRenderer/GODictionaryRenderer.h" \
    "$$SAMPLEPATHCPP/DisplayInformation/GOSymbols/GOSymbols.h" \
    "$$SAMPLEPATHCPP/DisplayInformation/IdentifyGraphics/IdentifyGraphics.h" \
    "$$SAMPLEPATHCPP/DisplayInformation/Picture_Marker_Symbol/Picture_Marker_Symbol.h" \
    "$$SAMPLEPATHCPP/DisplayInformation/QueryFeaturesWithArcadeExpression/QueryFeaturesWithArcadeExpression.h" \
    "$$SAMPLEPATHCPP/DisplayInformation/ReadSymbolsFromMobileStyle/ReadSymbolsFromMobileStyle.h" \
    "$$SAMPLEPATHCPP/DisplayInformation/ReadSymbolsFromMobileStyle/SymbolImageProvider.h" \
    "$$SAMPLEPATHCPP/DisplayInformation/ShowCallout/ShowCallout.h" \
    "$$SAMPLEPATHCPP/DisplayInformation/ShowLabelsOnLayers/ShowLabelsOnLayers.h" \
    "$$SAMPLEPATHCPP/DisplayInformation/ShowPopup/ShowPopup.h" \
    "$$SAMPLEPATHCPP/DisplayInformation/Simple_Marker_Symbol/Simple_Marker_Symbol.h" \
    "$$SAMPLEPATHCPP/DisplayInformation/Simple_Renderer/Simple_Renderer.h" \
    "$$SAMPLEPATHCPP/DisplayInformation/SketchOnMap/SketchOnMap.h" \
    "$$SAMPLEPATHCPP/DisplayInformation/SymbolizeShapefile/SymbolizeShapefile.h" \
    "$$SAMPLEPATHCPP/DisplayInformation/Unique_Value_Renderer/Unique_Value_Renderer.h" \
    "$$SAMPLEPATHCPP/EditData/AddFeaturesFeatureService/AddFeaturesFeatureService.h" \
    "$$SAMPLEPATHCPP/EditData/ContingentValues/ContingentValues.h" \
    "$$SAMPLEPATHCPP/EditData/DeleteFeaturesFeatureService/DeleteFeaturesFeatureService.h" \
    "$$SAMPLEPATHCPP/EditData/EditAndSyncFeatures/EditAndSyncFeatures.h" \
    "$$SAMPLEPATHCPP/EditData/EditFeatureAttachments/EditFeatureAttachments.h" \
    "$$SAMPLEPATHCPP/EditData/EditFeaturesWithFeatureLinkedAnnotation/EditFeaturesWithFeatureLinkedAnnotation.h" \
    "$$SAMPLEPATHCPP/EditData/EditKmlGroundOverlay/EditKmlGroundOverlay.h" \
    "$$SAMPLEPATHCPP/EditData/EditWithBranchVersioning/EditWithBranchVersioning.h" \
    "$$SAMPLEPATHCPP/EditData/UpdateAttributesFeatureService/UpdateAttributesFeatureService.h" \
    "$$SAMPLEPATHCPP/EditData/UpdateGeometryFeatureService/UpdateGeometryFeatureService.h" \
    "$$SAMPLEPATHCPP/Features/ControlTimeExtentTimeSlider/ControlTimeExtentTimeSlider.h" \
    "$$SAMPLEPATHCPP/Features/FeatureLayerChangeRenderer/FeatureLayerChangeRenderer.h" \
    "$$SAMPLEPATHCPP/Features/FeatureLayerDictionaryRenderer/FeatureLayerDictionaryRenderer.h" \
    "$$SAMPLEPATHCPP/Features/FeatureLayerFeatureService/FeatureLayerFeatureService.h" \
    "$$SAMPLEPATHCPP/Features/FeatureLayerGeodatabase/FeatureLayerGeodatabase.h" \
    "$$SAMPLEPATHCPP/Features/FeatureLayerGeoPackage/FeatureLayer_GeoPackage.h" \
    "$$SAMPLEPATHCPP/Features/FeatureLayerQuery/FeatureLayerQuery.h" \
    "$$SAMPLEPATHCPP/Features/FeatureLayerSelection/FeatureLayerSelection.h" \
    "$$SAMPLEPATHCPP/Features/FilterByDefinitionExpressionOrDisplayFilter/FilterByDefinitionExpressionOrDisplayFilter.h" \
    "$$SAMPLEPATHCPP/Features/GenerateGeodatabase/GenerateGeodatabase.h" \
    "$$SAMPLEPATHCPP/Features/ListRelatedFeatures/ListRelatedFeatures.h" \
    "$$SAMPLEPATHCPP/Features/ListRelatedFeatures/RelatedFeature.h" \
    "$$SAMPLEPATHCPP/Features/ListRelatedFeatures/RelatedFeatureListModel.h" \
    "$$SAMPLEPATHCPP/Features/ServiceFeatureTableCache/ServiceFeatureTableCache.h" \
    "$$SAMPLEPATHCPP/Features/ServiceFeatureTableManualCache/ServiceFeatureTableManualCache.h" \
    "$$SAMPLEPATHCPP/Features/ServiceFeatureTableNoCache/ServiceFeatureTableNoCache.h" \
    "$$SAMPLEPATHCPP/Geometry/Buffer/Buffer.h" \
    "$$SAMPLEPATHCPP/Geometry/ClipGeometry/ClipGeometry.h" \
    "$$SAMPLEPATHCPP/Geometry/ConvexHull/ConvexHull.h" \
    "$$SAMPLEPATHCPP/Geometry/CreateGeometries/CreateGeometries.h" \
    "$$SAMPLEPATHCPP/Geometry/CutGeometry/CutGeometry.h" \
    "$$SAMPLEPATHCPP/Geometry/DensifyAndGeneralize/DensifyAndGeneralize.h" \
    "$$SAMPLEPATHCPP/Geometry/FormatCoordinates/FormatCoordinates.h" \
    "$$SAMPLEPATHCPP/Geometry/GeodesicOperations/GeodesicOperations.h" \
    "$$SAMPLEPATHCPP/Geometry/ListTransformations/ListTransformations.h" \
    "$$SAMPLEPATHCPP/Geometry/NearestVertex/NearestVertex.h" \
    "$$SAMPLEPATHCPP/Geometry/ProjectGeometry/ProjectGeometry.h" \
    "$$SAMPLEPATHCPP/Geometry/SpatialOperations/SpatialOperations.h" \
    "$$SAMPLEPATHCPP/Geometry/SpatialRelationships/SpatialRelationships.h" \
    "$$SAMPLEPATHCPP/Layers/AddEncExchangeSet/AddEncExchangeSet.h" \
    "$$SAMPLEPATHCPP/Layers/ApplyMosaicRuleToRasters/ApplyMosaicRuleToRasters.h" \
    "$$SAMPLEPATHCPP/Layers/ApplyUniqueValuesWithAlternateSymbols/ApplyUniqueValuesWithAlternateSymbols.h" \
    "$$SAMPLEPATHCPP/Layers/ArcGISMapImageLayerUrl/ArcGISMapImageLayerUrl.h" \
    "$$SAMPLEPATHCPP/Layers/ArcGISTiledLayerUrl/ArcGISTiledLayerUrl.h" \
    "$$SAMPLEPATHCPP/Layers/BlendRasterLayer/BlendRasterLayer.h" \
    "$$SAMPLEPATHCPP/Layers/BrowseOGCAPIFeatureService/BrowseOGCAPIFeatureService.h" \
    "$$SAMPLEPATHCPP/Layers/BrowseWfsLayers/BrowseWfsLayers.h" \
    "$$SAMPLEPATHCPP/Layers/ChangeSublayerRenderer/ChangeSublayerRenderer.h" \
    "$$SAMPLEPATHCPP/Layers/ChangeSublayerVisibility/ChangeSublayerVisibility.h" \
    "$$SAMPLEPATHCPP/Layers/CreateAndSaveKmlFile/CreateAndSaveKmlFile.h" \
    "$$SAMPLEPATHCPP/Layers/DisplayAnnotation/DisplayAnnotation.h" \
    "$$SAMPLEPATHCPP/Layers/DisplayDimensions/DisplayDimensions.h" \
    "$$SAMPLEPATHCPP/Layers/DisplayKml/DisplayKml.h" \
    "$$SAMPLEPATHCPP/Layers/DisplayKmlNetworkLinks/DisplayKmlNetworkLinks.h" \
    "$$SAMPLEPATHCPP/Layers/DisplayOgcApiFeatureCollection/DisplayOgcApiFeatureCollection.h" \
    "$$SAMPLEPATHCPP/Layers/DisplaySubtypeFeatureLayer/DisplaySubtypeFeatureLayer.h" \
    "$$SAMPLEPATHCPP/Layers/DisplayWfsLayer/DisplayWfsLayer.h" \
    "$$SAMPLEPATHCPP/Layers/ExportTiles/ExportTiles.h" \
    "$$SAMPLEPATHCPP/Layers/Feature_Collection_Layer/Feature_Collection_Layer.h" \
    "$$SAMPLEPATHCPP/Layers/FeatureCollectionLayerFromPortal/FeatureCollectionLayerFromPortal.h" \
    "$$SAMPLEPATHCPP/Layers/FeatureCollectionLayerQuery/FeatureCollectionLayerQuery.h" \
    "$$SAMPLEPATHCPP/Layers/FeatureLayerRenderingModeMap/FeatureLayerRenderingModeMap.h" \
    "$$SAMPLEPATHCPP/Layers/FeatureLayerRenderingModeScene/FeatureLayerRenderingModeScene.h" \
    "$$SAMPLEPATHCPP/Layers/FeatureLayerShapefile/FeatureLayerShapefile.h" \
    "$$SAMPLEPATHCPP/Layers/GroupLayers/GroupLayers.h" \
    "$$SAMPLEPATHCPP/Layers/Hillshade_Renderer/Hillshade_Renderer.h" \
    "$$SAMPLEPATHCPP/Layers/IdentifyKmlFeatures/IdentifyKmlFeatures.h" \
    "$$SAMPLEPATHCPP/Layers/IdentifyRasterCell/IdentifyRasterCell.h" \
    "$$SAMPLEPATHCPP/Layers/ListKmlContents/ListKmlContents.h" \
    "$$SAMPLEPATHCPP/Layers/LoadWfsXmlQuery/LoadWfsXmlQuery.h" \
    "$$SAMPLEPATHCPP/Layers/ManageOperationalLayers/DrawOrderLayerListModel.h" \
    "$$SAMPLEPATHCPP/Layers/ManageOperationalLayers/ManageOperationalLayers.h" \
    "$$SAMPLEPATHCPP/Layers/OSM_Layer/OSM_Layer.h" \
    "$$SAMPLEPATHCPP/Layers/PlayAKmlTour/PlayAKmlTour.h" \
    "$$SAMPLEPATHCPP/Layers/QueryMapImageSublayer/QueryMapImageSublayer.h" \
    "$$SAMPLEPATHCPP/Layers/QueryOGCAPICQLFilters/QueryOGCAPICQLFilters.h" \
    "$$SAMPLEPATHCPP/Layers/RasterColormapRenderer/RasterColormapRenderer.h" \
    "$$SAMPLEPATHCPP/Layers/RasterFunctionService/RasterFunctionService.h" \
    "$$SAMPLEPATHCPP/Layers/RasterLayerFile/RasterLayerFile.h" \
    "$$SAMPLEPATHCPP/Layers/RasterLayerGeoPackage/RasterLayerGeoPackage.h" \
    "$$SAMPLEPATHCPP/Layers/RasterLayerService/RasterLayerService.h"\
    "$$SAMPLEPATHCPP/Layers/RasterRenderingRule/RasterRenderingRule.h" \
    "$$SAMPLEPATHCPP/Layers/RasterRgbRenderer/RasterRgbRenderer.h" \
    "$$SAMPLEPATHCPP/Layers/RasterStretchRenderer/RasterStretchRenderer.h" \
    "$$SAMPLEPATHCPP/Layers/StyleWmsLayer/StyleWmsLayer.h" \
    "$$SAMPLEPATHCPP/Layers/TileCacheLayer/TileCacheLayer.h" \
    "$$SAMPLEPATHCPP/Layers/VectorTiledLayerUrl/VectorTiledLayerUrl.h" \
    "$$SAMPLEPATHCPP/Layers/Web_Tiled_Layer/Web_Tiled_Layer.h" \
    "$$SAMPLEPATHCPP/Layers/WmsLayerUrl/WmsLayerUrl.h" \
    "$$SAMPLEPATHCPP/Layers/WMTS_Layer/WMTS_Layer.h" \
    "$$SAMPLEPATHCPP/Maps/ApplyScheduledMapUpdates/ApplyScheduledMapUpdates.h" \
    "$$SAMPLEPATHCPP/Maps/BrowseBuildingFloors/BrowseBuildingFloors.h" \
    "$$SAMPLEPATHCPP/Maps/ChangeBasemap/ChangeBasemap.h" \
    "$$SAMPLEPATHCPP/Maps/ChangeViewpoint/ChangeViewpoint.h" \
    "$$SAMPLEPATHCPP/Maps/CreateAndSaveMap/CreateAndSaveMap.h" \
    "$$SAMPLEPATHCPP/Maps/DisplayDeviceLocation/DisplayDeviceLocation.h" \
    "$$SAMPLEPATHCPP/Maps/DisplayDeviceLocationWithNmeaDataSources/DisplayDeviceLocationWithNmeaDataSources.h" \
    "$$SAMPLEPATHCPP/Maps/DisplayDrawingStatus/DisplayDrawingStatus.h" \
    "$$SAMPLEPATHCPP/Maps/DisplayLayerViewDrawState/DisplayLayerViewDrawState.h" \
    "$$SAMPLEPATHCPP/Maps/DisplayMap/DisplayMap.h" \
    "$$SAMPLEPATHCPP/Maps/DisplayOverviewMap/DisplayOverviewMap.h" \
    "$$SAMPLEPATHCPP/Maps/DownloadPreplannedMap/DownloadPreplannedMap.h" \
    "$$SAMPLEPATHCPP/Maps/GenerateOfflineMap_Overrides/GenerateOfflineMap_Overrides.h" \
    "$$SAMPLEPATHCPP/Maps/GenerateOfflineMap/GenerateOfflineMap.h" \
    "$$SAMPLEPATHCPP/Maps/GenerateOfflineMapLocalBasemap/GenerateOfflineMapLocalBasemap.h" \
    "$$SAMPLEPATHCPP/Maps/HonorMobileMapPackageExpiration/HonorMobileMapPackageExpiration.h" \
    "$$SAMPLEPATHCPP/Maps/IdentifyLayers/IdentifyLayers.h" \
    "$$SAMPLEPATHCPP/Maps/ManageBookmarks/ManageBookmarks.h" \
    "$$SAMPLEPATHCPP/Maps/MapLoaded/MapLoaded.h" \
    "$$SAMPLEPATHCPP/Maps/MapReferenceScale/MapReferenceScale.h" \
    "$$SAMPLEPATHCPP/Maps/MapRotation/MapRotation.h" \
    "$$SAMPLEPATHCPP/Maps/MinMaxScale/MinMaxScale.h" \
    "$$SAMPLEPATHCPP/Maps/MobileMap_SearchAndRoute/MobileMap_SearchAndRoute.h" \
    "$$SAMPLEPATHCPP/Maps/OpenMapUrl/OpenMapUrl.h" \
    "$$SAMPLEPATHCPP/Maps/OpenMobileMap_MapPackage/OpenMobileMap_MapPackage.h" \
    "$$SAMPLEPATHCPP/Maps/ReadGeoPackage/ReadGeoPackage.h" \
    "$$SAMPLEPATHCPP/Maps/SetInitialMapArea/SetInitialMapArea.h" \
    "$$SAMPLEPATHCPP/Maps/SetInitialMapLocation/SetInitialMapLocation.h" \
    "$$SAMPLEPATHCPP/Maps/SetMapSpatialReference/SetMapSpatialReference.h" \
    "$$SAMPLEPATHCPP/Maps/SetMaxExtent/SetMaxExtent.h" \
    "$$SAMPLEPATHCPP/Maps/ShowDeviceLocationUsingIndoorPositioning/IndoorsLocationDataSourceCreator.h" \
    "$$SAMPLEPATHCPP/Maps/ShowDeviceLocationUsingIndoorPositioning/ShowDeviceLocationUsingIndoorPositioning.h" \
    "$$SAMPLEPATHCPP/Maps/ShowLocationHistory/ShowLocationHistory.h" \
    "$$SAMPLEPATHCPP/Maps/ShowMagnifier/ShowMagnifier.h" \
    "$$SAMPLEPATHCPP/Maps/TakeScreenshot/MapImageProvider.h" \
    "$$SAMPLEPATHCPP/Maps/TakeScreenshot/TakeScreenshot.h" \
    "$$SAMPLEPATHCPP/Routing/ClosestFacility/ClosestFacility.h" \
    "$$SAMPLEPATHCPP/Routing/FindClosestFacilityToMultipleIncidentsService/FindClosestFacilityToMultipleIncidentsService.h" \
    "$$SAMPLEPATHCPP/Routing/FindRoute/FindRoute.h" \
    "$$SAMPLEPATHCPP/Routing/FindServiceAreasForMultipleFacilities/FindServiceAreasForMultipleFacilities.h" \
    "$$SAMPLEPATHCPP/Routing/NavigateRoute/NavigateRoute.h" \
    "$$SAMPLEPATHCPP/Routing/OfflineRouting/OfflineRouting.h" \
    "$$SAMPLEPATHCPP/Routing/RouteAroundBarriers/RouteAroundBarriers.h" \
    "$$SAMPLEPATHCPP/Routing/ServiceArea/ServiceArea.h" \
    "$$SAMPLEPATHCPP/Scenes/AddAPointSceneLayer/AddAPointSceneLayer.h" \
    "$$SAMPLEPATHCPP/Scenes/AddIntegratedMeshLayer/AddIntegratedMeshLayer.h" \
    "$$SAMPLEPATHCPP/Scenes/Animate3DSymbols/Animate3DSymbols.h" \
    "$$SAMPLEPATHCPP/Scenes/Animate3DSymbols/MissionData.h" \
    "$$SAMPLEPATHCPP/Scenes/AnimateImagesWithImageOverlay/AnimateImagesWithImageOverlay.h" \
    "$$SAMPLEPATHCPP/Scenes/BasicSceneView/BasicSceneView.h" \
    "$$SAMPLEPATHCPP/Scenes/ChangeAtmosphereEffect/ChangeAtmosphereEffect.h" \
    "$$SAMPLEPATHCPP/Scenes/ChooseCameraController/ChooseCameraController.h" \
    "$$SAMPLEPATHCPP/Scenes/CreateTerrainSurfaceFromLocalRaster/CreateTerrainSurfaceFromLocalRaster.h" \
    "$$SAMPLEPATHCPP/Scenes/CreateTerrainSurfaceFromLocalTilePackage/CreateTerrainSurfaceFromLocalTilePackage.h" \
    "$$SAMPLEPATHCPP/Scenes/Display3DLabelsInScene/Display3DLabelsInScene.h" \
    "$$SAMPLEPATHCPP/Scenes/DisplaySceneLayer/DisplaySceneLayer.h" \
    "$$SAMPLEPATHCPP/Scenes/DistanceCompositeSymbol/DistanceCompositeSymbol.h" \
    "$$SAMPLEPATHCPP/Scenes/ExtrudeGraphics/ExtrudeGraphics.h" \
    "$$SAMPLEPATHCPP/Scenes/FeatureLayerExtrusion/FeatureLayerExtrusion.h" \
    "$$SAMPLEPATHCPP/Scenes/GetElevationAtPoint/GetElevationAtPoint.h" \
    "$$SAMPLEPATHCPP/Scenes/OpenMobileScenePackage/OpenMobileScenePackage.h" \
    "$$SAMPLEPATHCPP/Scenes/OpenScene/OpenScene.h" \
    "$$SAMPLEPATHCPP/Scenes/OrbitCameraAroundObject/OrbitCameraAroundObject.h" \
    "$$SAMPLEPATHCPP/Scenes/RealisticLightingAndShadows/RealisticLightingAndShadows.h" \
    "$$SAMPLEPATHCPP/Scenes/SceneLayerSelection/SceneLayerSelection.h" \
    "$$SAMPLEPATHCPP/Scenes/ScenePropertiesExpressions/ScenePropertiesExpressions.h" \
    "$$SAMPLEPATHCPP/Scenes/SurfacePlacement/Surface_Placement.h" \
    "$$SAMPLEPATHCPP/Scenes/Symbols/Symbols.h" \
    "$$SAMPLEPATHCPP/Scenes/SyncMapViewSceneView/SyncMapViewSceneView.h" \
    "$$SAMPLEPATHCPP/Scenes/TerrainExaggeration/TerrainExaggeration.h" \
    "$$SAMPLEPATHCPP/Scenes/ViewContentBeneathTerrainSurface/ViewContentBeneathTerrainSurface.h" \
    "$$SAMPLEPATHCPP/Scenes/ViewPointCloudDataOffline/ViewPointCloudDataOffline.h" \
    "$$SAMPLEPATHCPP/Search/FindAddress/FindAddress.h" \
    "$$SAMPLEPATHCPP/Search/FindPlace/FindPlace.h" \
    "$$SAMPLEPATHCPP/Search/OfflineGeocode/OfflineGeocode.h" \
    "$$SAMPLEPATHCPP/Search/ReverseGeocodeOnline/ReverseGeocodeOnline.h" \
    "$$SAMPLEPATHCPP/Search/SearchDictionarySymbolStyle/SearchDictionarySymbolStyle.h" \
    "$$SAMPLEPATHCPP/UtilityNetwork/ConfigureSubnetworkTrace/ConfigureSubnetworkTrace.h" \
    "$$SAMPLEPATHCPP/UtilityNetwork/CreateLoadReport/CreateLoadReport.h" \
    "$$SAMPLEPATHCPP/UtilityNetwork/DisplayContentOfUtilityNetworkContainer/DisplayContentOfUtilityNetworkContainer.h" \
    "$$SAMPLEPATHCPP/UtilityNetwork/DisplayUtilityAssociations/DisplayUtilityAssociations.h" \
    "$$SAMPLEPATHCPP/UtilityNetwork/PerformValveIsolationTrace/PerformValveIsolationTrace.h" \
    "$$SAMPLEPATHCPP/UtilityNetwork/TraceUtilityNetwork/TraceUtilityNetwork.h" \

SOURCES += \
    "$$SAMPLEPATHCPP/Analysis/AnalyzeHotspots/AnalyzeHotspots.cpp" \
    "$$SAMPLEPATHCPP/Analysis/AnalyzeViewshed/AnalyzeViewshed.cpp" \
    "$$SAMPLEPATHCPP/Analysis/DistanceMeasurementAnalysis/DistanceMeasurementAnalysis.cpp" \
    "$$SAMPLEPATHCPP/Analysis/Geotriggers/Geotriggers.cpp" \
    "$$SAMPLEPATHCPP/Analysis/LineOfSightGeoElement/LineOfSightGeoElement.cpp" \
    "$$SAMPLEPATHCPP/Analysis/LineOfSightLocation/LineOfSightLocation.cpp" \
    "$$SAMPLEPATHCPP/Analysis/StatisticalQuery/StatisticalQuery.cpp" \
    "$$SAMPLEPATHCPP/Analysis/StatisticalQueryGroupSort/StatisticalQueryGroupSort.cpp" \
    "$$SAMPLEPATHCPP/Analysis/StatisticalQueryGroupSort/StatisticResultListModel.cpp" \
    "$$SAMPLEPATHCPP/Analysis/ViewshedCamera/ViewshedCamera.cpp" \
    "$$SAMPLEPATHCPP/Analysis/ViewshedGeoElement/ViewshedGeoElement.cpp" \
    "$$SAMPLEPATHCPP/Analysis/ViewshedLocation/ViewshedLocation.cpp" \
    "$$SAMPLEPATHCPP/CloudAndPortal/IntegratedWindowsAuthentication/IntegratedWindowsAuthentication.cpp" \
    "$$SAMPLEPATHCPP/CloudAndPortal/TokenAuthentication/TokenAuthentication.cpp" \
    "$$SAMPLEPATHCPP/DisplayInformation/AddGraphicsWithRenderer/AddGraphicsWithRenderer.cpp" \
    "$$SAMPLEPATHCPP/DisplayInformation/BuildLegend/BuildLegend.cpp" \
    "$$SAMPLEPATHCPP/DisplayInformation/ControlAnnotationSublayerVisibility/ControlAnnotationSublayerVisibility.cpp" \
    "$$SAMPLEPATHCPP/DisplayInformation/CreateSymbolStylesFromWebStyles/CreateSymbolStylesFromWebStyles.cpp" \
    "$$SAMPLEPATHCPP/DisplayInformation/CustomDictionaryStyle/CustomDictionaryStyle.cpp" \
    "$$SAMPLEPATHCPP/DisplayInformation/DisplayGrid/DisplayGrid.cpp" \
    "$$SAMPLEPATHCPP/DisplayInformation/GODictionaryRenderer_3D/GODictionaryRenderer_3D.cpp" \
    "$$SAMPLEPATHCPP/DisplayInformation/GODictionaryRenderer/GODictionaryRenderer.cpp" \
    "$$SAMPLEPATHCPP/DisplayInformation/GOSymbols/GOSymbols.cpp" \
    "$$SAMPLEPATHCPP/DisplayInformation/IdentifyGraphics/IdentifyGraphics.cpp" \
    "$$SAMPLEPATHCPP/DisplayInformation/Picture_Marker_Symbol/Picture_Marker_Symbol.cpp" \
    "$$SAMPLEPATHCPP/DisplayInformation/QueryFeaturesWithArcadeExpression/QueryFeaturesWithArcadeExpression.cpp" \
    "$$SAMPLEPATHCPP/DisplayInformation/ReadSymbolsFromMobileStyle/ReadSymbolsFromMobileStyle.cpp" \
    "$$SAMPLEPATHCPP/DisplayInformation/ReadSymbolsFromMobileStyle/SymbolImageProvider.cpp" \
    "$$SAMPLEPATHCPP/DisplayInformation/ShowCallout/ShowCallout.cpp" \
    "$$SAMPLEPATHCPP/DisplayInformation/ShowLabelsOnLayers/ShowLabelsOnLayers.cpp" \
    "$$SAMPLEPATHCPP/DisplayInformation/ShowPopup/ShowPopup.cpp" \
    "$$SAMPLEPATHCPP/DisplayInformation/Simple_Marker_Symbol/Simple_Marker_Symbol.cpp" \
    "$$SAMPLEPATHCPP/DisplayInformation/Simple_Renderer/Simple_Renderer.cpp" \
    "$$SAMPLEPATHCPP/DisplayInformation/SketchOnMap/SketchOnMap.cpp" \
    "$$SAMPLEPATHCPP/DisplayInformation/SymbolizeShapefile/SymbolizeShapefile.cpp" \
    "$$SAMPLEPATHCPP/DisplayInformation/Unique_Value_Renderer/Unique_Value_Renderer.cpp" \
    "$$SAMPLEPATHCPP/EditData/AddFeaturesFeatureService/AddFeaturesFeatureService.cpp" \
    "$$SAMPLEPATHCPP/EditData/ContingentValues/ContingentValues.cpp" \
    "$$SAMPLEPATHCPP/EditData/DeleteFeaturesFeatureService/DeleteFeaturesFeatureService.cpp" \
    "$$SAMPLEPATHCPP/EditData/EditAndSyncFeatures/EditAndSyncFeatures.cpp" \
    "$$SAMPLEPATHCPP/EditData/EditFeatureAttachments/EditFeatureAttachments.cpp" \
    "$$SAMPLEPATHCPP/EditData/EditFeaturesWithFeatureLinkedAnnotation/EditFeaturesWithFeatureLinkedAnnotation.cpp" \
    "$$SAMPLEPATHCPP/EditData/EditKmlGroundOverlay/EditKmlGroundOverlay.cpp" \
    "$$SAMPLEPATHCPP/EditData/EditWithBranchVersioning/EditWithBranchVersioning.cpp" \
    "$$SAMPLEPATHCPP/EditData/UpdateAttributesFeatureService/UpdateAttributesFeatureService.cpp" \
    "$$SAMPLEPATHCPP/EditData/UpdateGeometryFeatureService/UpdateGeometryFeatureService.cpp" \
    "$$SAMPLEPATHCPP/Features/ControlTimeExtentTimeSlider/ControlTimeExtentTimeSlider.cpp" \
    "$$SAMPLEPATHCPP/Features/FeatureLayerChangeRenderer/FeatureLayerChangeRenderer.cpp" \
    "$$SAMPLEPATHCPP/Features/FeatureLayerDictionaryRenderer/FeatureLayerDictionaryRenderer.cpp" \
    "$$SAMPLEPATHCPP/Features/FeatureLayerFeatureService/FeatureLayerFeatureService.cpp" \
    "$$SAMPLEPATHCPP/Features/FeatureLayerGeodatabase/FeatureLayerGeodatabase.cpp" \
    "$$SAMPLEPATHCPP/Features/FeatureLayerGeoPackage/FeatureLayer_GeoPackage.cpp" \
    "$$SAMPLEPATHCPP/Features/FeatureLayerQuery/FeatureLayerQuery.cpp" \
    "$$SAMPLEPATHCPP/Features/FeatureLayerSelection/FeatureLayerSelection.cpp" \
    "$$SAMPLEPATHCPP/Features/FilterByDefinitionExpressionOrDisplayFilter/FilterByDefinitionExpressionOrDisplayFilter.cpp" \
    "$$SAMPLEPATHCPP/Features/GenerateGeodatabase/GenerateGeodatabase.cpp" \
    "$$SAMPLEPATHCPP/Features/ListRelatedFeatures/ListRelatedFeatures.cpp" \
    "$$SAMPLEPATHCPP/Features/ListRelatedFeatures/RelatedFeature.cpp" \
    "$$SAMPLEPATHCPP/Features/ListRelatedFeatures/RelatedFeatureListModel.cpp" \
    "$$SAMPLEPATHCPP/Features/ServiceFeatureTableCache/ServiceFeatureTableCache.cpp" \
    "$$SAMPLEPATHCPP/Features/ServiceFeatureTableManualCache/ServiceFeatureTableManualCache.cpp" \
    "$$SAMPLEPATHCPP/Features/ServiceFeatureTableNoCache/ServiceFeatureTableNoCache.cpp" \
    "$$SAMPLEPATHCPP/Geometry/Buffer/Buffer.cpp" \
    "$$SAMPLEPATHCPP/Geometry/ClipGeometry/ClipGeometry.cpp" \
    "$$SAMPLEPATHCPP/Geometry/ConvexHull/ConvexHull.cpp" \
    "$$SAMPLEPATHCPP/Geometry/CreateGeometries/CreateGeometries.cpp" \
    "$$SAMPLEPATHCPP/Geometry/CutGeometry/CutGeometry.cpp" \
    "$$SAMPLEPATHCPP/Geometry/DensifyAndGeneralize/DensifyAndGeneralize.cpp" \
    "$$SAMPLEPATHCPP/Geometry/FormatCoordinates/FormatCoordinates.cpp" \
    "$$SAMPLEPATHCPP/Geometry/GeodesicOperations/GeodesicOperations.cpp" \
    "$$SAMPLEPATHCPP/Geometry/ListTransformations/ListTransformations.cpp" \
    "$$SAMPLEPATHCPP/Geometry/NearestVertex/NearestVertex.cpp" \
    "$$SAMPLEPATHCPP/Geometry/ProjectGeometry/ProjectGeometry.cpp" \
    "$$SAMPLEPATHCPP/Geometry/SpatialOperations/SpatialOperations.cpp" \
    "$$SAMPLEPATHCPP/Geometry/SpatialRelationships/SpatialRelationships.cpp" \
    "$$SAMPLEPATHCPP/Layers/AddEncExchangeSet/AddEncExchangeSet.cpp" \
    "$$SAMPLEPATHCPP/Layers/ApplyMosaicRuleToRasters/ApplyMosaicRuleToRasters.cpp" \
    "$$SAMPLEPATHCPP/Layers/ApplyUniqueValuesWithAlternateSymbols/ApplyUniqueValuesWithAlternateSymbols.cpp" \
    "$$SAMPLEPATHCPP/Layers/ArcGISMapImageLayerUrl/ArcGISMapImageLayerUrl.cpp" \
    "$$SAMPLEPATHCPP/Layers/ArcGISTiledLayerUrl/ArcGISTiledLayerUrl.cpp" \
    "$$SAMPLEPATHCPP/Layers/BlendRasterLayer/BlendRasterLayer.cpp" \
    "$$SAMPLEPATHCPP/Layers/BrowseOGCAPIFeatureService/BrowseOGCAPIFeatureService.cpp" \
    "$$SAMPLEPATHCPP/Layers/BrowseWfsLayers/BrowseWfsLayers.cpp" \
    "$$SAMPLEPATHCPP/Layers/ChangeSublayerRenderer/ChangeSublayerRenderer.cpp" \
    "$$SAMPLEPATHCPP/Layers/ChangeSublayerVisibility/ChangeSublayerVisibility.cpp" \
    "$$SAMPLEPATHCPP/Layers/CreateAndSaveKmlFile/CreateAndSaveKmlFile.cpp" \
    "$$SAMPLEPATHCPP/Layers/DisplayAnnotation/DisplayAnnotation.cpp" \
    "$$SAMPLEPATHCPP/Layers/DisplayDimensions/DisplayDimensions.cpp" \
    "$$SAMPLEPATHCPP/Layers/DisplayKml/DisplayKml.cpp" \
    "$$SAMPLEPATHCPP/Layers/DisplayKmlNetworkLinks/DisplayKmlNetworkLinks.cpp" \
    "$$SAMPLEPATHCPP/Layers/DisplayOgcApiFeatureCollection/DisplayOgcApiFeatureCollection.cpp" \
    "$$SAMPLEPATHCPP/Layers/DisplaySubtypeFeatureLayer/DisplaySubtypeFeatureLayer.cpp" \
    "$$SAMPLEPATHCPP/Layers/DisplayWfsLayer/DisplayWfsLayer.cpp" \
    "$$SAMPLEPATHCPP/Layers/ExportTiles/ExportTiles.cpp" \
    "$$SAMPLEPATHCPP/Layers/Feature_Collection_Layer/Feature_Collection_Layer.cpp" \
    "$$SAMPLEPATHCPP/Layers/FeatureCollectionLayerFromPortal/FeatureCollectionLayerFromPortal.cpp" \
    "$$SAMPLEPATHCPP/Layers/FeatureCollectionLayerQuery/FeatureCollectionLayerQuery.cpp" \
    "$$SAMPLEPATHCPP/Layers/FeatureLayerRenderingModeMap/FeatureLayerRenderingModeMap.cpp" \
    "$$SAMPLEPATHCPP/Layers/FeatureLayerRenderingModeScene/FeatureLayerRenderingModeScene.cpp" \
    "$$SAMPLEPATHCPP/Layers/FeatureLayerShapefile/FeatureLayerShapefile.cpp" \
    "$$SAMPLEPATHCPP/Layers/GroupLayers/GroupLayers.cpp" \
    "$$SAMPLEPATHCPP/Layers/Hillshade_Renderer/Hillshade_Renderer.cpp" \
    "$$SAMPLEPATHCPP/Layers/IdentifyKmlFeatures/IdentifyKmlFeatures.cpp" \
    "$$SAMPLEPATHCPP/Layers/IdentifyRasterCell/IdentifyRasterCell.cpp" \
    "$$SAMPLEPATHCPP/Layers/ListKmlContents/ListKmlContents.cpp" \
    "$$SAMPLEPATHCPP/Layers/LoadWfsXmlQuery/LoadWfsXmlQuery.cpp" \
    "$$SAMPLEPATHCPP/Layers/ManageOperationalLayers/DrawOrderLayerListModel.cpp" \
    "$$SAMPLEPATHCPP/Layers/ManageOperationalLayers/ManageOperationalLayers.cpp" \
    "$$SAMPLEPATHCPP/Layers/OSM_Layer/OSM_Layer.cpp" \
    "$$SAMPLEPATHCPP/Layers/PlayAKmlTour/PlayAKmlTour.cpp" \
    "$$SAMPLEPATHCPP/Layers/QueryMapImageSublayer/QueryMapImageSublayer.cpp" \
    "$$SAMPLEPATHCPP/Layers/QueryOGCAPICQLFilters/QueryOGCAPICQLFilters.cpp" \
    "$$SAMPLEPATHCPP/Layers/RasterColormapRenderer/RasterColormapRenderer.cpp" \
    "$$SAMPLEPATHCPP/Layers/RasterFunctionService/RasterFunctionService.cpp" \
    "$$SAMPLEPATHCPP/Layers/RasterLayerFile/RasterLayerFile.cpp" \
    "$$SAMPLEPATHCPP/Layers/RasterLayerGeoPackage/RasterLayerGeoPackage.cpp" \
    "$$SAMPLEPATHCPP/Layers/RasterLayerService/RasterLayerService.cpp" \
    "$$SAMPLEPATHCPP/Layers/RasterRenderingRule/RasterRenderingRule.cpp" \
    "$$SAMPLEPATHCPP/Layers/RasterRgbRenderer/RasterRgbRenderer.cpp" \
    "$$SAMPLEPATHCPP/Layers/RasterStretchRenderer/RasterStretchRenderer.cpp" \
    "$$SAMPLEPATHCPP/Layers/StyleWmsLayer/StyleWmsLayer.cpp" \
    "$$SAMPLEPATHCPP/Layers/TileCacheLayer/TileCacheLayer.cpp" \
    "$$SAMPLEPATHCPP/Layers/VectorTiledLayerUrl/VectorTiledLayerUrl.cpp" \
    "$$SAMPLEPATHCPP/Layers/Web_Tiled_Layer/Web_Tiled_Layer.cpp" \
    "$$SAMPLEPATHCPP/Layers/WmsLayerUrl/WmsLayerUrl.cpp" \
    "$$SAMPLEPATHCPP/Layers/WMTS_Layer/WMTS_Layer.cpp" \
    "$$SAMPLEPATHCPP/Maps/ApplyScheduledMapUpdates/ApplyScheduledMapUpdates.cpp" \
    "$$SAMPLEPATHCPP/Maps/BrowseBuildingFloors/BrowseBuildingFloors.cpp" \
    "$$SAMPLEPATHCPP/Maps/ChangeBasemap/ChangeBasemap.cpp" \
    "$$SAMPLEPATHCPP/Maps/ChangeViewpoint/ChangeViewpoint.cpp" \
    "$$SAMPLEPATHCPP/Maps/CreateAndSaveMap/CreateAndSaveMap.cpp" \
    "$$SAMPLEPATHCPP/Maps/DisplayDeviceLocation/DisplayDeviceLocation.cpp" \
    "$$SAMPLEPATHCPP/Maps/DisplayDeviceLocationWithNmeaDataSources/DisplayDeviceLocationWithNmeaDataSources.cpp" \
    "$$SAMPLEPATHCPP/Maps/DisplayDrawingStatus/DisplayDrawingStatus.cpp" \
    "$$SAMPLEPATHCPP/Maps/DisplayLayerViewDrawState/DisplayLayerViewDrawState.cpp" \
    "$$SAMPLEPATHCPP/Maps/DisplayMap/DisplayMap.cpp" \
    "$$SAMPLEPATHCPP/Maps/DisplayOverviewMap/DisplayOverviewMap.cpp" \
    "$$SAMPLEPATHCPP/Maps/DownloadPreplannedMap/DownloadPreplannedMap.cpp" \
    "$$SAMPLEPATHCPP/Maps/GenerateOfflineMap_Overrides/GenerateOfflineMap_Overrides.cpp" \
    "$$SAMPLEPATHCPP/Maps/GenerateOfflineMap/GenerateOfflineMap.cpp" \
    "$$SAMPLEPATHCPP/Maps/GenerateOfflineMapLocalBasemap/GenerateOfflineMapLocalBasemap.cpp" \
    "$$SAMPLEPATHCPP/Maps/HonorMobileMapPackageExpiration/HonorMobileMapPackageExpiration.cpp" \
    "$$SAMPLEPATHCPP/Maps/IdentifyLayers/IdentifyLayers.cpp" \
    "$$SAMPLEPATHCPP/Maps/ManageBookmarks/ManageBookmarks.cpp" \
    "$$SAMPLEPATHCPP/Maps/MapLoaded/MapLoaded.cpp" \
    "$$SAMPLEPATHCPP/Maps/MapReferenceScale/MapReferenceScale.cpp" \
    "$$SAMPLEPATHCPP/Maps/MapRotation/MapRotation.cpp" \
    "$$SAMPLEPATHCPP/Maps/MinMaxScale/MinMaxScale.cpp" \
    "$$SAMPLEPATHCPP/Maps/MobileMap_SearchAndRoute/MobileMap_SearchAndRoute.cpp" \
    "$$SAMPLEPATHCPP/Maps/OpenMapUrl/OpenMapUrl.cpp" \
    "$$SAMPLEPATHCPP/Maps/OpenMobileMap_MapPackage/OpenMobileMap_MapPackage.cpp" \
    "$$SAMPLEPATHCPP/Maps/ReadGeoPackage/ReadGeoPackage.cpp" \
    "$$SAMPLEPATHCPP/Maps/SetInitialMapArea/SetInitialMapArea.cpp" \
    "$$SAMPLEPATHCPP/Maps/SetInitialMapLocation/SetInitialMapLocation.cpp" \
    "$$SAMPLEPATHCPP/Maps/SetMapSpatialReference/SetMapSpatialReference.cpp" \
    "$$SAMPLEPATHCPP/Maps/SetMaxExtent/SetMaxExtent.cpp" \
    "$$SAMPLEPATHCPP/Maps/ShowDeviceLocationUsingIndoorPositioning/IndoorsLocationDataSourceCreator.cpp" \
    "$$SAMPLEPATHCPP/Maps/ShowDeviceLocationUsingIndoorPositioning/ShowDeviceLocationUsingIndoorPositioning.cpp" \
    "$$SAMPLEPATHCPP/Maps/ShowLocationHistory/ShowLocationHistory.cpp" \
    "$$SAMPLEPATHCPP/Maps/ShowMagnifier/ShowMagnifier.cpp" \
    "$$SAMPLEPATHCPP/Maps/TakeScreenshot/MapImageProvider.cpp" \
    "$$SAMPLEPATHCPP/Maps/TakeScreenshot/TakeScreenshot.cpp" \
    "$$SAMPLEPATHCPP/Routing/ClosestFacility/ClosestFacility.cpp" \
    "$$SAMPLEPATHCPP/Routing/FindClosestFacilityToMultipleIncidentsService/FindClosestFacilityToMultipleIncidentsService.cpp" \
    "$$SAMPLEPATHCPP/Routing/FindRoute/FindRoute.cpp" \
    "$$SAMPLEPATHCPP/Routing/FindServiceAreasForMultipleFacilities/FindServiceAreasForMultipleFacilities.cpp" \
    "$$SAMPLEPATHCPP/Routing/NavigateRoute/NavigateRoute.cpp" \
    "$$SAMPLEPATHCPP/Routing/OfflineRouting/OfflineRouting.cpp" \
    "$$SAMPLEPATHCPP/Routing/RouteAroundBarriers/RouteAroundBarriers.cpp" \
    "$$SAMPLEPATHCPP/Routing/ServiceArea/ServiceArea.cpp" \
    "$$SAMPLEPATHCPP/Scenes/AddAPointSceneLayer/AddAPointSceneLayer.cpp" \
    "$$SAMPLEPATHCPP/Scenes/AddIntegratedMeshLayer/AddIntegratedMeshLayer.cpp" \
    "$$SAMPLEPATHCPP/Scenes/Animate3DSymbols/Animate3DSymbols.cpp" \
    "$$SAMPLEPATHCPP/Scenes/Animate3DSymbols/MissionData.cpp" \
    "$$SAMPLEPATHCPP/Scenes/AnimateImagesWithImageOverlay/AnimateImagesWithImageOverlay.cpp" \
    "$$SAMPLEPATHCPP/Scenes/BasicSceneView/BasicSceneView.cpp" \
    "$$SAMPLEPATHCPP/Scenes/ChangeAtmosphereEffect/ChangeAtmosphereEffect.cpp" \
    "$$SAMPLEPATHCPP/Scenes/ChooseCameraController/ChooseCameraController.cpp" \
    "$$SAMPLEPATHCPP/Scenes/CreateTerrainSurfaceFromLocalRaster/CreateTerrainSurfaceFromLocalRaster.cpp" \
    "$$SAMPLEPATHCPP/Scenes/CreateTerrainSurfaceFromLocalTilePackage/CreateTerrainSurfaceFromLocalTilePackage.cpp" \
    "$$SAMPLEPATHCPP/Scenes/Display3DLabelsInScene/Display3DLabelsInScene.cpp" \
    "$$SAMPLEPATHCPP/Scenes/DisplaySceneLayer/DisplaySceneLayer.cpp" \
    "$$SAMPLEPATHCPP/Scenes/DistanceCompositeSymbol/DistanceCompositeSymbol.cpp" \
    "$$SAMPLEPATHCPP/Scenes/ExtrudeGraphics/ExtrudeGraphics.cpp" \
    "$$SAMPLEPATHCPP/Scenes/FeatureLayerExtrusion/FeatureLayerExtrusion.cpp" \
    "$$SAMPLEPATHCPP/Scenes/GetElevationAtPoint/GetElevationAtPoint.cpp" \
    "$$SAMPLEPATHCPP/Scenes/OpenMobileScenePackage/OpenMobileScenePackage.cpp" \
    "$$SAMPLEPATHCPP/Scenes/OpenScene/OpenScene.cpp" \
    "$$SAMPLEPATHCPP/Scenes/OrbitCameraAroundObject/OrbitCameraAroundObject.cpp" \
    "$$SAMPLEPATHCPP/Scenes/RealisticLightingAndShadows/RealisticLightingAndShadows.cpp" \
    "$$SAMPLEPATHCPP/Scenes/SceneLayerSelection/SceneLayerSelection.cpp" \
    "$$SAMPLEPATHCPP/Scenes/ScenePropertiesExpressions/ScenePropertiesExpressions.cpp" \
    "$$SAMPLEPATHCPP/Scenes/SurfacePlacement/Surface_Placement.cpp" \
    "$$SAMPLEPATHCPP/Scenes/Symbols/Symbols.cpp" \
    "$$SAMPLEPATHCPP/Scenes/SyncMapViewSceneView/SyncMapViewSceneView.cpp" \
    "$$SAMPLEPATHCPP/Scenes/TerrainExaggeration/TerrainExaggeration.cpp" \
    "$$SAMPLEPATHCPP/Scenes/ViewContentBeneathTerrainSurface/ViewContentBeneathTerrainSurface.cpp" \
    "$$SAMPLEPATHCPP/Scenes/ViewPointCloudDataOffline/ViewPointCloudDataOffline.cpp" \
    "$$SAMPLEPATHCPP/Search/FindAddress/FindAddress.cpp" \
    "$$SAMPLEPATHCPP/Search/FindPlace/FindPlace.cpp" \
    "$$SAMPLEPATHCPP/Search/OfflineGeocode/OfflineGeocode.cpp" \
    "$$SAMPLEPATHCPP/Search/ReverseGeocodeOnline/ReverseGeocodeOnline.cpp" \
    "$$SAMPLEPATHCPP/Search/SearchDictionarySymbolStyle/SearchDictionarySymbolStyle.cpp" \
    "$$SAMPLEPATHCPP/UtilityNetwork/ConfigureSubnetworkTrace/ConfigureSubnetworkTrace.cpp" \
    "$$SAMPLEPATHCPP/UtilityNetwork/CreateLoadReport/CreateLoadReport.cpp" \
    "$$SAMPLEPATHCPP/UtilityNetwork/DisplayContentOfUtilityNetworkContainer/DisplayContentOfUtilityNetworkContainer.cpp" \
    "$$SAMPLEPATHCPP/UtilityNetwork/DisplayUtilityAssociations/DisplayUtilityAssociations.cpp" \
    "$$SAMPLEPATHCPP/UtilityNetwork/PerformValveIsolationTrace/PerformValveIsolationTrace.cpp" \
    "$$SAMPLEPATHCPP/UtilityNetwork/TraceUtilityNetwork/TraceUtilityNetwork.cpp"


RESOURCES += \
    "$$SAMPLEPATHCPP/Analysis/AnalyzeHotspots/AnalyzeHotspots.qrc" \
    "$$SAMPLEPATHCPP/Analysis/AnalyzeViewshed/AnalyzeViewshed.qrc" \
    "$$SAMPLEPATHCPP/Analysis/DistanceMeasurementAnalysis/DistanceMeasurementAnalysis.qrc" \
    "$$SAMPLEPATHCPP/Analysis/Geotriggers/Geotriggers.qrc" \
    "$$SAMPLEPATHCPP/Analysis/LineOfSightGeoElement/LineOfSightGeoElement.qrc" \
    "$$SAMPLEPATHCPP/Analysis/LineOfSightLocation/LineOfSightLocation.qrc" \
    "$$SAMPLEPATHCPP/Analysis/StatisticalQuery/StatisticalQuery.qrc" \
    "$$SAMPLEPATHCPP/Analysis/StatisticalQueryGroupSort/StatisticalQueryGroupSort.qrc" \
    "$$SAMPLEPATHCPP/Analysis/ViewshedCamera/ViewshedCamera.qrc" \
    "$$SAMPLEPATHCPP/Analysis/ViewshedGeoElement/ViewshedGeoElement.qrc" \
    "$$SAMPLEPATHCPP/Analysis/ViewshedLocation/ViewshedLocation.qrc" \
    "$$SAMPLEPATHCPP/CloudAndPortal/IntegratedWindowsAuthentication/IntegratedWindowsAuthentication.qrc" \
    "$$SAMPLEPATHCPP/CloudAndPortal/TokenAuthentication/TokenAuthentication.qrc" \
    "$$SAMPLEPATHCPP/DisplayInformation/AddGraphicsWithRenderer/AddGraphicsWithRenderer.qrc" \
    "$$SAMPLEPATHCPP/DisplayInformation/BuildLegend/BuildLegend.qrc" \
    "$$SAMPLEPATHCPP/DisplayInformation/ControlAnnotationSublayerVisibility/ControlAnnotationSublayerVisibility.qrc" \
    "$$SAMPLEPATHCPP/DisplayInformation/CreateSymbolStylesFromWebStyles/CreateSymbolStylesFromWebStyles.qrc" \
    "$$SAMPLEPATHCPP/DisplayInformation/CustomDictionaryStyle/CustomDictionaryStyle.qrc" \
    "$$SAMPLEPATHCPP/DisplayInformation/DisplayGrid/DisplayGrid.qrc" \
    "$$SAMPLEPATHCPP/DisplayInformation/GODictionaryRenderer_3D/GODictionaryRenderer_3D.qrc" \
    "$$SAMPLEPATHCPP/DisplayInformation/GODictionaryRenderer/GODictionaryRenderer.qrc" \
    "$$SAMPLEPATHCPP/DisplayInformation/GOSymbols/GOSymbols.qrc" \
    "$$SAMPLEPATHCPP/DisplayInformation/IdentifyGraphics/IdentifyGraphics.qrc" \
    "$$SAMPLEPATHCPP/DisplayInformation/Picture_Marker_Symbol/Picture_Marker_Symbol.qrc" \
    "$$SAMPLEPATHCPP/DisplayInformation/QueryFeaturesWithArcadeExpression/QueryFeaturesWithArcadeExpression.qrc" \
    "$$SAMPLEPATHCPP/DisplayInformation/ReadSymbolsFromMobileStyle/ReadSymbolsFromMobileStyle.qrc" \
    "$$SAMPLEPATHCPP/DisplayInformation/ShowCallout/ShowCallout.qrc" \
    "$$SAMPLEPATHCPP/DisplayInformation/ShowLabelsOnLayers/ShowLabelsOnLayers.qrc" \
    "$$SAMPLEPATHCPP/DisplayInformation/ShowPopup/ShowPopup.qrc" \
    "$$SAMPLEPATHCPP/DisplayInformation/Simple_Marker_Symbol/Simple_Marker_Symbol.qrc" \
    "$$SAMPLEPATHCPP/DisplayInformation/Simple_Renderer/Simple_Renderer.qrc" \
    "$$SAMPLEPATHCPP/DisplayInformation/SketchOnMap/SketchOnMap.qrc" \
    "$$SAMPLEPATHCPP/DisplayInformation/SymbolizeShapefile/SymbolizeShapefile.qrc" \
    "$$SAMPLEPATHCPP/DisplayInformation/Unique_Value_Renderer/Unique_Value_Renderer.qrc" \
    "$$SAMPLEPATHCPP/EditData/AddFeaturesFeatureService/AddFeaturesFeatureService.qrc" \
    "$$SAMPLEPATHCPP/EditData/ContingentValues/ContingentValues.qrc" \
    "$$SAMPLEPATHCPP/EditData/DeleteFeaturesFeatureService/DeleteFeaturesFeatureService.qrc" \
    "$$SAMPLEPATHCPP/EditData/EditAndSyncFeatures/EditAndSyncFeatures.qrc" \
    "$$SAMPLEPATHCPP/EditData/EditFeatureAttachments/EditFeatureAttachments.qrc" \
    "$$SAMPLEPATHCPP/EditData/EditFeaturesWithFeatureLinkedAnnotation/EditFeaturesWithFeatureLinkedAnnotation.qrc" \
    "$$SAMPLEPATHCPP/EditData/EditKmlGroundOverlay/EditKmlGroundOverlay.qrc" \
    "$$SAMPLEPATHCPP/EditData/EditWithBranchVersioning/EditWithBranchVersioning.qrc" \
    "$$SAMPLEPATHCPP/EditData/UpdateAttributesFeatureService/UpdateAttributesFeatureService.qrc" \
    "$$SAMPLEPATHCPP/EditData/UpdateGeometryFeatureService/UpdateGeometryFeatureService.qrc" \
    "$$SAMPLEPATHCPP/Features/ControlTimeExtentTimeSlider/ControlTimeExtentTimeSlider.qrc" \
    "$$SAMPLEPATHCPP/Features/FeatureLayerChangeRenderer/FeatureLayerChangeRenderer.qrc" \
    "$$SAMPLEPATHCPP/Features/FeatureLayerDictionaryRenderer/FeatureLayerDictionaryRenderer.qrc" \
    "$$SAMPLEPATHCPP/Features/FeatureLayerFeatureService/FeatureLayerFeatureService.qrc" \
    "$$SAMPLEPATHCPP/Features/FeatureLayerGeodatabase/FeatureLayerGeodatabase.qrc" \
    "$$SAMPLEPATHCPP/Features/FeatureLayerGeoPackage/FeatureLayer_GeoPackage.qrc" \
    "$$SAMPLEPATHCPP/Features/FeatureLayerQuery/FeatureLayerQuery.qrc" \
    "$$SAMPLEPATHCPP/Features/FeatureLayerSelection/FeatureLayerSelection.qrc" \
    "$$SAMPLEPATHCPP/Features/FilterByDefinitionExpressionOrDisplayFilter/FilterByDefinitionExpressionOrDisplayFilter.qrc" \
    "$$SAMPLEPATHCPP/Features/GenerateGeodatabase/GenerateGeodatabase.qrc" \
    "$$SAMPLEPATHCPP/Features/ListRelatedFeatures/ListRelatedFeatures.qrc" \
    "$$SAMPLEPATHCPP/Features/ServiceFeatureTableCache/ServiceFeatureTableCache.qrc" \
    "$$SAMPLEPATHCPP/Features/ServiceFeatureTableManualCache/ServiceFeatureTableManualCache.qrc" \
    "$$SAMPLEPATHCPP/Features/ServiceFeatureTableNoCache/ServiceFeatureTableNoCache.qrc" \
    "$$SAMPLEPATHCPP/Geometry/Buffer/Buffer.qrc" \
    "$$SAMPLEPATHCPP/Geometry/ClipGeometry/ClipGeometry.qrc" \
    "$$SAMPLEPATHCPP/Geometry/ConvexHull/ConvexHull.qrc" \
    "$$SAMPLEPATHCPP/Geometry/CreateGeometries/CreateGeometries.qrc" \
    "$$SAMPLEPATHCPP/Geometry/CutGeometry/CutGeometry.qrc" \
    "$$SAMPLEPATHCPP/Geometry/DensifyAndGeneralize/DensifyAndGeneralize.qrc" \
    "$$SAMPLEPATHCPP/Geometry/FormatCoordinates/FormatCoordinates.qrc" \
    "$$SAMPLEPATHCPP/Geometry/GeodesicOperations/GeodesicOperations.qrc" \
    "$$SAMPLEPATHCPP/Geometry/ListTransformations/ListTransformations.qrc" \
    "$$SAMPLEPATHCPP/Geometry/NearestVertex/NearestVertex.qrc" \
    "$$SAMPLEPATHCPP/Geometry/ProjectGeometry/ProjectGeometry.qrc" \
    "$$SAMPLEPATHCPP/Geometry/SpatialOperations/SpatialOperations.qrc" \
    "$$SAMPLEPATHCPP/Geometry/SpatialRelationships/SpatialRelationships.qrc" \
    "$$SAMPLEPATHCPP/Layers/AddEncExchangeSet/AddEncExchangeSet.qrc" \
    "$$SAMPLEPATHCPP/Layers/ApplyMosaicRuleToRasters/ApplyMosaicRuleToRasters.qrc" \
    "$$SAMPLEPATHCPP/Layers/ApplyUniqueValuesWithAlternateSymbols/ApplyUniqueValuesWithAlternateSymbols.qrc" \
    "$$SAMPLEPATHCPP/Layers/ArcGISMapImageLayerUrl/ArcGISMapImageLayerUrl.qrc" \
    "$$SAMPLEPATHCPP/Layers/ArcGISTiledLayerUrl/ArcGISTiledLayerUrl.qrc" \
    "$$SAMPLEPATHCPP/Layers/BlendRasterLayer/BlendRasterLayer.qrc" \
    "$$SAMPLEPATHCPP/Layers/BrowseOGCAPIFeatureService/BrowseOGCAPIFeatureService.qrc" \
    "$$SAMPLEPATHCPP/Layers/BrowseWfsLayers/BrowseWfsLayers.qrc" \
    "$$SAMPLEPATHCPP/Layers/ChangeSublayerRenderer/ChangeSublayerRenderer.qrc" \
    "$$SAMPLEPATHCPP/Layers/ChangeSublayerVisibility/ChangeSublayerVisibility.qrc" \
    "$$SAMPLEPATHCPP/Layers/CreateAndSaveKmlFile/CreateAndSaveKmlFile.qrc" \
    "$$SAMPLEPATHCPP/Layers/DisplayAnnotation/DisplayAnnotation.qrc" \
    "$$SAMPLEPATHCPP/Layers/DisplayDimensions/DisplayDimensions.qrc" \
    "$$SAMPLEPATHCPP/Layers/DisplayKml/DisplayKml.qrc" \
    "$$SAMPLEPATHCPP/Layers/DisplayKmlNetworkLinks/DisplayKmlNetworkLinks.qrc" \
    "$$SAMPLEPATHCPP/Layers/DisplayOgcApiFeatureCollection/DisplayOgcApiFeatureCollection.qrc" \
    "$$SAMPLEPATHCPP/Layers/DisplaySubtypeFeatureLayer/DisplaySubtypeFeatureLayer.qrc" \
    "$$SAMPLEPATHCPP/Layers/DisplayWfsLayer/DisplayWfsLayer.qrc" \
    "$$SAMPLEPATHCPP/Layers/ExportTiles/ExportTiles.qrc" \
    "$$SAMPLEPATHCPP/Layers/Feature_Collection_Layer/Feature_Collection_Layer.qrc" \
    "$$SAMPLEPATHCPP/Layers/FeatureCollectionLayerFromPortal/FeatureCollectionLayerFromPortal.qrc" \
    "$$SAMPLEPATHCPP/Layers/FeatureCollectionLayerQuery/FeatureCollectionLayerQuery.qrc" \
    "$$SAMPLEPATHCPP/Layers/FeatureLayerRenderingModeMap/FeatureLayerRenderingModeMap.qrc" \
    "$$SAMPLEPATHCPP/Layers/FeatureLayerRenderingModeScene/FeatureLayerRenderingModeScene.qrc" \
    "$$SAMPLEPATHCPP/Layers/FeatureLayerShapefile/FeatureLayerShapefile.qrc" \
    "$$SAMPLEPATHCPP/Layers/GroupLayers/GroupLayers.qrc" \
    "$$SAMPLEPATHCPP/Layers/Hillshade_Renderer/Hillshade_Renderer.qrc" \
    "$$SAMPLEPATHCPP/Layers/IdentifyKmlFeatures/IdentifyKmlFeatures.qrc" \
    "$$SAMPLEPATHCPP/Layers/IdentifyRasterCell/IdentifyRasterCell.qrc" \
    "$$SAMPLEPATHCPP/Layers/ListKmlContents/ListKmlContents.qrc" \
    "$$SAMPLEPATHCPP/Layers/LoadWfsXmlQuery/LoadWfsXmlQuery.qrc" \
    "$$SAMPLEPATHCPP/Layers/ManageOperationalLayers/ManageOperationalLayers.qrc" \
    "$$SAMPLEPATHCPP/Layers/OSM_Layer/OSM_Layer.qrc" \
    "$$SAMPLEPATHCPP/Layers/PlayAKmlTour/PlayAKmlTour.qrc" \
    "$$SAMPLEPATHCPP/Layers/QueryMapImageSublayer/QueryMapImageSublayer.qrc" \
    "$$SAMPLEPATHCPP/Layers/QueryOGCAPICQLFilters/QueryOGCAPICQLFilters.qrc" \
    "$$SAMPLEPATHCPP/Layers/RasterColormapRenderer/RasterColormapRenderer.qrc" \
    "$$SAMPLEPATHCPP/Layers/RasterFunctionService/RasterFunctionService.qrc" \
    "$$SAMPLEPATHCPP/Layers/RasterLayerFile/RasterLayerFile.qrc" \
    "$$SAMPLEPATHCPP/Layers/RasterLayerGeoPackage/RasterLayerGeoPackage.qrc" \
    "$$SAMPLEPATHCPP/Layers/RasterLayerService/RasterLayerService.qrc" \
    "$$SAMPLEPATHCPP/Layers/RasterRenderingRule/RasterRenderingRule.qrc" \
    "$$SAMPLEPATHCPP/Layers/RasterRgbRenderer/RasterRgbRenderer.qrc" \
    "$$SAMPLEPATHCPP/Layers/RasterStretchRenderer/RasterStretchRenderer.qrc" \
    "$$SAMPLEPATHCPP/Layers/StyleWmsLayer/StyleWmsLayer.qrc" \
    "$$SAMPLEPATHCPP/Layers/TileCacheLayer/TileCacheLayer.qrc" \
    "$$SAMPLEPATHCPP/Layers/VectorTiledLayerUrl/VectorTiledLayerUrl.qrc" \
    "$$SAMPLEPATHCPP/Layers/Web_Tiled_Layer/Web_Tiled_Layer.qrc" \
    "$$SAMPLEPATHCPP/Layers/WmsLayerUrl/WmsLayerUrl.qrc" \
    "$$SAMPLEPATHCPP/Layers/WMTS_Layer/WMTS_Layer.qrc" \
    "$$SAMPLEPATHCPP/Maps/ApplyScheduledMapUpdates/ApplyScheduledMapUpdates.qrc" \
    "$$SAMPLEPATHCPP/Maps/BrowseBuildingFloors/BrowseBuildingFloors.qrc" \
    "$$SAMPLEPATHCPP/Maps/ChangeBasemap/ChangeBasemap.qrc" \
    "$$SAMPLEPATHCPP/Maps/ChangeViewpoint/ChangeViewpoint.qrc" \
    "$$SAMPLEPATHCPP/Maps/CreateAndSaveMap/CreateAndSaveMap.qrc" \
    "$$SAMPLEPATHCPP/Maps/DisplayDeviceLocation/DisplayDeviceLocation.qrc" \
    "$$SAMPLEPATHCPP/Maps/DisplayDeviceLocationWithNmeaDataSources/DisplayDeviceLocationWithNmeaDataSources.qrc" \
    "$$SAMPLEPATHCPP/Maps/DisplayDrawingStatus/DisplayDrawingStatus.qrc" \
    "$$SAMPLEPATHCPP/Maps/DisplayLayerViewDrawState/DisplayLayerViewDrawState.qrc" \
    "$$SAMPLEPATHCPP/Maps/DisplayMap/DisplayMap.qrc" \
    "$$SAMPLEPATHCPP/Maps/DisplayOverviewMap/DisplayOverviewMap.qrc" \
    "$$SAMPLEPATHCPP/Maps/DownloadPreplannedMap/DownloadPreplannedMap.qrc" \
    "$$SAMPLEPATHCPP/Maps/GenerateOfflineMap_Overrides/GenerateOfflineMap_Overrides.qrc" \
    "$$SAMPLEPATHCPP/Maps/GenerateOfflineMap/GenerateOfflineMap.qrc" \
    "$$SAMPLEPATHCPP/Maps/GenerateOfflineMapLocalBasemap/GenerateOfflineMapLocalBasemap.qrc" \
    "$$SAMPLEPATHCPP/Maps/HonorMobileMapPackageExpiration/HonorMobileMapPackageExpiration.qrc" \
    "$$SAMPLEPATHCPP/Maps/IdentifyLayers/IdentifyLayers.qrc" \
    "$$SAMPLEPATHCPP/Maps/ManageBookmarks/ManageBookmarks.qrc" \
    "$$SAMPLEPATHCPP/Maps/MapLoaded/MapLoaded.qrc" \
    "$$SAMPLEPATHCPP/Maps/MapReferenceScale/MapReferenceScale.qrc" \
    "$$SAMPLEPATHCPP/Maps/MapRotation/MapRotation.qrc" \
    "$$SAMPLEPATHCPP/Maps/MinMaxScale/MinMaxScale.qrc" \
    "$$SAMPLEPATHCPP/Maps/MobileMap_SearchAndRoute/MobileMap_SearchAndRoute.qrc" \
    "$$SAMPLEPATHCPP/Maps/OpenMapUrl/OpenMapUrl.qrc" \
    "$$SAMPLEPATHCPP/Maps/OpenMobileMap_MapPackage/OpenMobileMap_MapPackage.qrc" \
    "$$SAMPLEPATHCPP/Maps/ReadGeoPackage/ReadGeoPackage.qrc" \
    "$$SAMPLEPATHCPP/Maps/SetInitialMapArea/SetInitialMapArea.qrc" \
    "$$SAMPLEPATHCPP/Maps/SetInitialMapLocation/SetInitialMapLocation.qrc" \
    "$$SAMPLEPATHCPP/Maps/SetMapSpatialReference/SetMapSpatialReference.qrc" \
    "$$SAMPLEPATHCPP/Maps/SetMaxExtent/SetMaxExtent.qrc" \
    "$$SAMPLEPATHCPP/Maps/ShowDeviceLocationUsingIndoorPositioning/ShowDeviceLocationUsingIndoorPositioning.qrc" \
    "$$SAMPLEPATHCPP/Maps/ShowLocationHistory/ShowLocationHistory.qrc" \
    "$$SAMPLEPATHCPP/Maps/ShowMagnifier/ShowMagnifier.qrc" \
    "$$SAMPLEPATHCPP/Maps/TakeScreenshot/TakeScreenshot.qrc" \
    "$$SAMPLEPATHCPP/Routing/ClosestFacility/ClosestFacility.qrc" \
    "$$SAMPLEPATHCPP/Routing/FindClosestFacilityToMultipleIncidentsService/FindClosestFacilityToMultipleIncidentsService.qrc" \
    "$$SAMPLEPATHCPP/Routing/FindRoute/FindRoute.qrc" \
    "$$SAMPLEPATHCPP/Routing/FindServiceAreasForMultipleFacilities/FindServiceAreasForMultipleFacilities.qrc" \
    "$$SAMPLEPATHCPP/Routing/NavigateRoute/NavigateRoute.qrc" \
    "$$SAMPLEPATHCPP/Routing/OfflineRouting/OfflineRouting.qrc" \
    "$$SAMPLEPATHCPP/Routing/RouteAroundBarriers/RouteAroundBarriers.qrc" \
    "$$SAMPLEPATHCPP/Routing/ServiceArea/ServiceArea.qrc" \
    "$$SAMPLEPATHCPP/Scenes/AddAPointSceneLayer/AddAPointSceneLayer.qrc" \
    "$$SAMPLEPATHCPP/Scenes/AddIntegratedMeshLayer/AddIntegratedMeshLayer.qrc" \
    "$$SAMPLEPATHCPP/Scenes/Animate3DSymbols/Animate3DSymbols.qrc" \
    "$$SAMPLEPATHCPP/Scenes/AnimateImagesWithImageOverlay/AnimateImagesWithImageOverlay.qrc" \
    "$$SAMPLEPATHCPP/Scenes/BasicSceneView/BasicSceneView.qrc" \
    "$$SAMPLEPATHCPP/Scenes/ChangeAtmosphereEffect/ChangeAtmosphereEffect.qrc" \
    "$$SAMPLEPATHCPP/Scenes/ChooseCameraController/ChooseCameraController.qrc" \
    "$$SAMPLEPATHCPP/Scenes/CreateTerrainSurfaceFromLocalRaster/CreateTerrainSurfaceFromLocalRaster.qrc" \
    "$$SAMPLEPATHCPP/Scenes/CreateTerrainSurfaceFromLocalTilePackage/CreateTerrainSurfaceFromLocalTilePackage.qrc" \
    "$$SAMPLEPATHCPP/Scenes/Display3DLabelsInScene/Display3DLabelsInScene.qrc" \
    "$$SAMPLEPATHCPP/Scenes/DisplaySceneLayer/DisplaySceneLayer.qrc" \
    "$$SAMPLEPATHCPP/Scenes/DistanceCompositeSymbol/DistanceCompositeSymbol.qrc" \
    "$$SAMPLEPATHCPP/Scenes/ExtrudeGraphics/ExtrudeGraphics.qrc" \
    "$$SAMPLEPATHCPP/Scenes/FeatureLayerExtrusion/FeatureLayerExtrusion.qrc" \
    "$$SAMPLEPATHCPP/Scenes/GetElevationAtPoint/GetElevationAtPoint.qrc" \
    "$$SAMPLEPATHCPP/Scenes/OpenMobileScenePackage/OpenMobileScenePackage.qrc" \
    "$$SAMPLEPATHCPP/Scenes/OpenScene/OpenScene.qrc" \
    "$$SAMPLEPATHCPP/Scenes/OrbitCameraAroundObject/OrbitCameraAroundObject.qrc" \
    "$$SAMPLEPATHCPP/Scenes/RealisticLightingAndShadows/RealisticLightingAndShadows.qrc" \
    "$$SAMPLEPATHCPP/Scenes/SceneLayerSelection/SceneLayerSelection.qrc" \
    "$$SAMPLEPATHCPP/Scenes/ScenePropertiesExpressions/ScenePropertiesExpressions.qrc" \
    "$$SAMPLEPATHCPP/Scenes/SurfacePlacement/Surface_Placement.qrc" \
    "$$SAMPLEPATHCPP/Scenes/Symbols/Symbols.qrc" \
    "$$SAMPLEPATHCPP/Scenes/SyncMapViewSceneView/SyncMapViewSceneView.qrc" \
    "$$SAMPLEPATHCPP/Scenes/TerrainExaggeration/TerrainExaggeration.qrc" \
    "$$SAMPLEPATHCPP/Scenes/ViewContentBeneathTerrainSurface/ViewContentBeneathTerrainSurface.qrc" \
    "$$SAMPLEPATHCPP/Scenes/ViewPointCloudDataOffline/ViewPointCloudDataOffline.qrc" \
    "$$SAMPLEPATHCPP/Search/FindAddress/FindAddress.qrc" \
    "$$SAMPLEPATHCPP/Search/FindPlace/FindPlace.qrc" \
    "$$SAMPLEPATHCPP/Search/OfflineGeocode/OfflineGeocode.qrc" \
    "$$SAMPLEPATHCPP/Search/ReverseGeocodeOnline/ReverseGeocodeOnline.qrc" \
    "$$SAMPLEPATHCPP/Search/SearchDictionarySymbolStyle/SearchDictionarySymbolStyle.qrc" \
    "$$SAMPLEPATHCPP/UtilityNetwork/ConfigureSubnetworkTrace/ConfigureSubnetworkTrace.qrc" \
    "$$SAMPLEPATHCPP/UtilityNetwork/CreateLoadReport/CreateLoadReport.qrc" \
    "$$SAMPLEPATHCPP/UtilityNetwork/DisplayContentOfUtilityNetworkContainer/DisplayContentOfUtilityNetworkContainer.qrc" \
    "$$SAMPLEPATHCPP/UtilityNetwork/DisplayUtilityAssociations/DisplayUtilityAssociations.qrc" \
    "$$SAMPLEPATHCPP/UtilityNetwork/PerformValveIsolationTrace/PerformValveIsolationTrace.qrc" \
    "$$SAMPLEPATHCPP/UtilityNetwork/TraceUtilityNetwork/TraceUtilityNetwork.qrc"

# Local Server Only (Linux and Windows)
!android:!ios:!macx {
  INCLUDEPATH += \
    "$$SAMPLEPATHCPP/LocalServer/LocalServerFeatureLayer" \
    "$$SAMPLEPATHCPP/LocalServer/LocalServerGeoprocessing" \
    "$$SAMPLEPATHCPP/LocalServer/LocalServerMapImageLayer" \
    "$$SAMPLEPATHCPP/LocalServer/LocalServerServices"

  HEADERS += \
    "$$SAMPLEPATHCPP/LocalServer/LocalServerFeatureLayer/LocalServerFeatureLayer.h" \
    "$$SAMPLEPATHCPP/LocalServer/LocalServerGeoprocessing/LocalServerGeoprocessing.h" \
    "$$SAMPLEPATHCPP/LocalServer/LocalServerMapImageLayer/LocalServerMapImageLayer.h" \
    "$$SAMPLEPATHCPP/LocalServer/LocalServerServices/LocalServerServices.h"

  SOURCES += \
    "$$SAMPLEPATHCPP/LocalServer/LocalServerFeatureLayer/LocalServerFeatureLayer.cpp" \
    "$$SAMPLEPATHCPP/LocalServer/LocalServerGeoprocessing/LocalServerGeoprocessing.cpp" \
    "$$SAMPLEPATHCPP/LocalServer/LocalServerMapImageLayer/LocalServerMapImageLayer.cpp" \
    "$$SAMPLEPATHCPP/LocalServer/LocalServerServices/LocalServerServices.cpp"

  RESOURCES += \
    "$$SAMPLEPATHCPP/LocalServer/LocalServerFeatureLayer/LocalServerFeatureLayer.qrc" \
    "$$SAMPLEPATHCPP/LocalServer/LocalServerGeoprocessing/LocalServerGeoprocessing.qrc" \
    "$$SAMPLEPATHCPP/LocalServer/LocalServerMapImageLayer/LocalServerMapImageLayer.qrc" \
    "$$SAMPLEPATHCPP/LocalServer/LocalServerServices/LocalServerServices.qrc"
}

# Exclude samples with WebView from macOS and Linux
win32|android|ios {
  DEFINES += SHOW_PORTAL_SAMPLES

  INCLUDEPATH += \
    "$$SAMPLEPATHCPP/CloudAndPortal/AddItemsToPortal" \
    "$$SAMPLEPATHCPP/CloudAndPortal/PortalUserInfo" \
    "$$SAMPLEPATHCPP/CloudAndPortal/SearchForWebmap" \
    "$$SAMPLEPATHCPP/CloudAndPortal/ShowOrgBasemaps"

  HEADERS += \
    "$$SAMPLEPATHCPP/CloudAndPortal/AddItemsToPortal/AddItemsToPortal.h" \
    "$$SAMPLEPATHCPP/CloudAndPortal/PortalUserInfo/PortalUserInfo.h" \
    "$$SAMPLEPATHCPP/CloudAndPortal/SearchForWebmap/SearchForWebmap.h" \
    "$$SAMPLEPATHCPP/CloudAndPortal/ShowOrgBasemaps/ShowOrgBasemaps.h"

  SOURCES += \
    "$$SAMPLEPATHCPP/CloudAndPortal/AddItemsToPortal/AddItemsToPortal.cpp" \
    "$$SAMPLEPATHCPP/CloudAndPortal/PortalUserInfo/PortalUserInfo.cpp" \
    "$$SAMPLEPATHCPP/CloudAndPortal/SearchForWebmap/SearchForWebmap.cpp" \
    "$$SAMPLEPATHCPP/CloudAndPortal/ShowOrgBasemaps/ShowOrgBasemaps.cpp"

  RESOURCES += \
    "$$SAMPLEPATHCPP/CloudAndPortal/AddItemsToPortal/AddItemsToPortal.qrc" \
    "$$SAMPLEPATHCPP/CloudAndPortal/PortalUserInfo/PortalUserInfo.qrc" \
    "$$SAMPLEPATHCPP/CloudAndPortal/SearchForWebmap/SearchForWebmap.qrc" \
    "$$SAMPLEPATHCPP/CloudAndPortal/ShowOrgBasemaps/ShowOrgBasemaps.qrc"
}

# Exclude Raster Function File from macOS
!macx {
  DEFINES += SHOW_RASTER_FUNCTION_SAMPLE

  INCLUDEPATH += \
    "$$SAMPLEPATHCPP/Layers/RasterFunctionFile"

  HEADERS += \
    "$$SAMPLEPATHCPP/Layers/RasterFunctionFile/RasterFunctionFile.h"

  SOURCES += \
    "$$SAMPLEPATHCPP/Layers/RasterFunctionFile/RasterFunctionFile.cpp"

  RESOURCES += \
    "$$SAMPLEPATHCPP/Layers/RasterFunctionFile/RasterFunctionFile.qrc"
}
